In [1]:
import numpy as np
import re

### Task 1
### HardCode method

In [150]:
with open('sentences.txt', 'r') as f:
    sentences = f.read().lower().split('\n')
sentences

['in comparison to dogs, cats have not undergone major changes during the domestication process.',
 'as cat simply catenates streams of bytes, it can be also used to concatenate binary files, where it will just concatenate sequence of bytes.',
 'a common interactive use of cat for a single file is to output the content of a file to standard output.',
 'cats can hear sounds too faint or too high in frequency for human ears, such as those made by mice and other small animals.',
 'in one, people deliberately tamed cats in a process of artificial selection, as they were useful predators of vermin.',
 'the domesticated cat and its closest wild ancestor are both diploid organisms that possess 38 chromosomes and roughly 20,000 genes.',
 'domestic cats are similar in size to the other members of the genus felis, typically weighing between 4 and 5 kg (8.8 and 11.0 lb).',
 'however, if the output is piped or redirected, cat is unnecessary.',
 'cat with one named file is safer where human error i

In [72]:
test = [[i for i in re.split('[^a-z]', sentence) if i != ''] for sentence in sentences.split('\n')]
unique = [j for i in test for j in i]
unique = list(set(unique))
print(len(unique))

254


In [63]:
set(unique) - set(unique_words)

{'based', 'left', 'non', 'right', 's', 't', 'won'}

In [84]:
tokens = [[i for i in re.split('[^a-z]', sentence) if i != ''] for sentence in sentences]
tokens

[['in',
  'comparison',
  'to',
  'dogs',
  'cats',
  'have',
  'not',
  'undergone',
  'major',
  'changes',
  'during',
  'the',
  'domestication',
  'process'],
 ['as',
  'cat',
  'simply',
  'catenates',
  'streams',
  'of',
  'bytes',
  'it',
  'can',
  'be',
  'also',
  'used',
  'to',
  'concatenate',
  'binary',
  'files',
  'where',
  'it',
  'will',
  'just',
  'concatenate',
  'sequence',
  'of',
  'bytes'],
 ['a',
  'common',
  'interactive',
  'use',
  'of',
  'cat',
  'for',
  'a',
  'single',
  'file',
  'is',
  'to',
  'output',
  'the',
  'content',
  'of',
  'a',
  'file',
  'to',
  'standard',
  'output'],
 ['cats',
  'can',
  'hear',
  'sounds',
  'too',
  'faint',
  'or',
  'too',
  'high',
  'in',
  'frequency',
  'for',
  'human',
  'ears',
  'such',
  'as',
  'those',
  'made',
  'by',
  'mice',
  'and',
  'other',
  'small',
  'animals'],
 ['in',
  'one',
  'people',
  'deliberately',
  'tamed',
  'cats',
  'in',
  'a',
  'process',
  'of',
  'artificial',
  's

In [85]:
unique_words = list(set([word for sentence in tokens for word in sentence]))
word2idx = {word : i for i, word in enumerate(unique_words)}
word2idx

{'piped': 0,
 'part': 1,
 'roughly': 2,
 'dogs': 3,
 'arguments': 4,
 'apple': 5,
 'based': 6,
 'release': 7,
 'that': 8,
 'contains': 9,
 'available': 10,
 'intel': 11,
 'recent': 12,
 'deliberately': 13,
 'felis': 14,
 'offered': 15,
 'for': 16,
 'high': 17,
 'standard': 18,
 'people': 19,
 'size': 20,
 'cats': 21,
 'tamed': 22,
 'binary': 23,
 'time': 24,
 'right': 25,
 'through': 26,
 'now': 27,
 'releasing': 28,
 'lb': 29,
 'received': 30,
 'too': 31,
 'domestication': 32,
 'since': 33,
 'with': 34,
 'osx': 35,
 'releases': 36,
 'use': 37,
 'tiger': 38,
 'online': 39,
 'undergone': 40,
 'os': 41,
 'won': 42,
 'has': 43,
 'are': 44,
 'files': 45,
 'using': 46,
 'receives': 47,
 'displays': 48,
 'and': 49,
 'unix': 50,
 'redirection': 51,
 'according': 52,
 'version': 53,
 'lion': 54,
 'they': 55,
 'safari': 56,
 'those': 57,
 'fifth': 58,
 'file': 59,
 'mavericks': 60,
 'drive': 61,
 'if': 62,
 'later': 63,
 'two': 64,
 'purchase': 65,
 'it': 66,
 'vermin': 67,
 'some': 68,
 'on': 

In [86]:
count_matrix = np.zeros((len(sentences), len(unique_words)))
count_matrix.shape

(22, 254)

In [97]:
for i, sentence in enumerate(tokens):
    for token in sentence:
        count_matrix[i, word2idx[token]] = sentence.count(token)
count_matrix

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 1., 0., 1.]])

In [2]:
def cos_distance(x, y):
    return 1 - x@y/(np.sqrt(x@x)*np.sqrt(y@y))

In [119]:
distances = np.array([cos_distance(count_matrix[0], count_matrix[i]) for i in range(1, count_matrix.shape[0])])
distances

array([0.95275444, 0.86447381, 0.89517152, 0.77708871, 0.94023857,
       0.73273876, 0.92587507, 0.88427249, 0.90550888, 0.83281654,
       0.88047714, 0.83964325, 0.87035926, 0.87401184, 0.94427218,
       0.84063619, 0.9566445 , 0.94427218, 0.88854436, 0.84275727,
       0.82503645])

In [125]:
nearest_sentences = np.argsort(distances)[:2] + 1
nearest_sentences

array([6, 4], dtype=int64)

In [132]:
with open('solution.txt', 'w') as f:
    f.write(f'{nearest_sentences[0]} {nearest_sentences[1]}')

### Better Method

In [151]:
sentences = [re.sub(r'\d', ' ', sentence) for sentence in sentences]

In [159]:
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics.pairwise import cosine_distances

vectorizer = CountVectorizer()
count_matrix = vectorizer.fit_transform(sentences)
count_matrix = count_matrix.toarray()
count_matrix.shape

(22, 250)

In [166]:
distances = cosine_distances(count_matrix[0].reshape(1, -1), count_matrix[1:])[0]
nearest_sentences = np.argsort(distances)[:2] + 1
nearest_sentences

array([6, 4], dtype=int64)

### Task 2
### Нужно доказать, что неравенство $d(x, z) \leq d(x, y) + d(y, z)$, где $d(x, z) - $ косинусное расстояние между x и z. Косинусное расстояние не подчиняется неравенству треугольнику так как можно взять пример при котором не будет выполняться условие для неравенства треугольника. Например: $\vec{x} = (1, 1) \ \ \vec{z} = (0, 1) \ \ \vec{y} = (0, 0.2)$ В итоге получается: 
### $d(x, z) = 1 - \frac{xz}{|x||z|} = 1 > d(x, y) + d(y, z) = 2-\frac{xy}{|x||y|} - \frac{yz}{|y||z|} \approx 0.58$ то есть неравенство треугольника не выполняется. Косинусное расстояние хоть и является метрикой расстояние в евклидовом пространстве, но он является неправильной метрикой расстояния поэтому чтобы это исправить придумали угловое расстояние $angular \ distance = \frac{\cos^{-1}(cosine \ similarity)}{\pi}$. При замене неравенство треугольника выполняется $d(x, z) = 0.5 <= d(x, y) + d(y, z) = 0.5000000000000001$